config/routes.rb
Progeny2::Application.routes.draw do
  resources :species

end

app/models/species.rb
class Species < ActiveRecord::Base
  # Return a status string of a particular species
  def full_species
    "#{name} #{identification} has #{(assimilated? ? ' ' : 'not')}been assimilated."

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  # GET /species
  # GET /species.json
  def index
    @species = Species.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @species }
    end
  end

  # GET /species/1
  # GET /species/1.json
  def show
    @species = Species.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @species }
    end
  end

  # GET /species/new
  # GET /species/new.json
  def new
    @species = Species.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @species }
    end
  end

  # GET /species/1/edit
  def edit
    @species = Species.find(params[:id])
  end

  # POST /species
  # POST /species.json
  def create
    @species = Species.new(params[:species])

    respond_to do |format|
      if @species.save
        format.html { redirect_to @species, notice: 'Species was successfully created.' }
        format.json { render json: @species, status: :created, location: @species }
      else
        format.html { render action: "new" }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /species/1
  # PUT /species/1.json
  def update
    @species = Species.find(params[:id])

    respond_to do |format|
      if @species.update_attributes(params[:species])
        format.html { redirect_to @species, notice: 'Species was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /species/1
  # DELETE /species/1.json
  def destroy
    @species = Species.find(params[:id])
    @species.destroy

    respond_to do |format|
      format.html { redirect_to species_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Progeny2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/species/_form.html.erb
<%= form_for(@species) do |f| %>
  <% if @species.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@species.errors.count, "error") %> prohibited this species from being saved:</h2>

      <ul>
      <% @species.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :identification %><br />
    <%= f.number_field :identification %>
  </div>
  <div class="field">
    <%= f.label :assimilated %><br />
    <%= f.check_box :assimilated %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/species/edit.html.erb
<h1>Editing species</h1>

<%= render 'form' %>

<%= link_to 'Show', @species %> |
<%= link_to 'Back', species_index_path %>

app/views/species/index.html.erb
<h1>Listing species</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Identification</th>
    <th>Assimilated</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @species.each do |species| %>
  <tr>
    <td><%= species.name %></td>
    <td><%= species.identification %></td>
    <td><%= species.assimilated %></td>
    <td><%= link_to 'Show', species %></td>
    <td><%= link_to 'Edit', edit_species_path(species) %></td>
    <td><%= link_to 'Destroy', species, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Species', new_species_path %>

app/views/species/new.html.erb
<h1>New species</h1>

<%= render 'form' %>

<%= link_to 'Back', species_index_path %>

app/views/species/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @species.name %>
</p>

<p>
  <b>Identification:</b>
  <%= @species.identification %>
</p>

<p>
  <b>Assimilated:</b>
  <%= @species.assimilated %>
</p>


<%= link_to 'Edit', edit_species_path(@species) %> |
<%= link_to 'Back', species_index_path %>